// Code generated by qtc from "main.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line cmd/templates/main.qtpl:1
package templates

//line cmd/templates/main.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line cmd/templates/main.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line cmd/templates/main.qtpl:1
func StreamComponent(qw422016 *qt422016.Writer, name string) {
//line cmd/templates/main.qtpl:1
	qw422016.N().S(`
    import React from 'react';
    import { View } from 'react-native';

    // import { Container } from './styles';

    const `)
//line cmd/templates/main.qtpl:7
	qw422016.E().S(name)
//line cmd/templates/main.qtpl:7
	qw422016.N().S(` = () => {
    return <View />;
    }

    export default `)
//line cmd/templates/main.qtpl:11
	qw422016.E().S(name)
//line cmd/templates/main.qtpl:11
	qw422016.N().S(`;
`)
//line cmd/templates/main.qtpl:12
}

//line cmd/templates/main.qtpl:12
func WriteComponent(qq422016 qtio422016.Writer, name string) {
//line cmd/templates/main.qtpl:12
	qw422016 := qt422016.AcquireWriter(qq422016)
//line cmd/templates/main.qtpl:12
	StreamComponent(qw422016, name)
//line cmd/templates/main.qtpl:12
	qt422016.ReleaseWriter(qw422016)
//line cmd/templates/main.qtpl:12
}

//line cmd/templates/main.qtpl:12
func Component(name string) string {
//line cmd/templates/main.qtpl:12
	qb422016 := qt422016.AcquireByteBuffer()
//line cmd/templates/main.qtpl:12
	WriteComponent(qb422016, name)
//line cmd/templates/main.qtpl:12
	qs422016 := string(qb422016.B)
//line cmd/templates/main.qtpl:12
	qt422016.ReleaseByteBuffer(qb422016)
//line cmd/templates/main.qtpl:12
	return qs422016
//line cmd/templates/main.qtpl:12
}

//line cmd/templates/main.qtpl:13
func StreamScreen(qw422016 *qt422016.Writer, name string) {
//line cmd/templates/main.qtpl:13
	qw422016.N().S(`
    import React from 'react';
    import { View } from 'react-native';

    // import { Container } from './styles';

    const `)
//line cmd/templates/main.qtpl:19
	qw422016.E().S(name)
//line cmd/templates/main.qtpl:19
	qw422016.N().S(` = () => {
    return <View />;
    }

    export default `)
//line cmd/templates/main.qtpl:23
	qw422016.E().S(name)
//line cmd/templates/main.qtpl:23
	qw422016.N().S(`;
`)
//line cmd/templates/main.qtpl:24
}

//line cmd/templates/main.qtpl:24
func WriteScreen(qq422016 qtio422016.Writer, name string) {
//line cmd/templates/main.qtpl:24
	qw422016 := qt422016.AcquireWriter(qq422016)
//line cmd/templates/main.qtpl:24
	StreamScreen(qw422016, name)
//line cmd/templates/main.qtpl:24
	qt422016.ReleaseWriter(qw422016)
//line cmd/templates/main.qtpl:24
}

//line cmd/templates/main.qtpl:24
func Screen(name string) string {
//line cmd/templates/main.qtpl:24
	qb422016 := qt422016.AcquireByteBuffer()
//line cmd/templates/main.qtpl:24
	WriteScreen(qb422016, name)
//line cmd/templates/main.qtpl:24
	qs422016 := string(qb422016.B)
//line cmd/templates/main.qtpl:24
	qt422016.ReleaseByteBuffer(qb422016)
//line cmd/templates/main.qtpl:24
	return qs422016
//line cmd/templates/main.qtpl:24
}
